[package]
name = "http"
version = "0.2.0"
authors = ["Cesbo Developers Team"]
edition = "2018"
publish = false

[dependencies]
pest = "2.1"
pest_derive = "2.1"
base64 = "0.12"
openssl = "0.10"
libflate = "1.0"

[features]
static = ["openssl/vendored"]
